apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    name: nginx
    tier: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.configMap.port }}