apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    tier: db
spec:
  replicas: {{ .Values.Deployment.replicas }}
  selector:
    matchLabels:
      name: mysql
      tier: db
  template:
    metadata:
      labels:
        name: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: devopsrikanth/mysql:{{ .Values.Deployment.imageversion }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "ExpenseApp@1"
        - name: MYSQL_USER
          value: "expense"
        - name: MYSQL_PASSWORD
          value: "ExpenseApp@1"
        - name: MYSQL_DATABASE
          value: "transactions"



