apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
    tier: db
spec:
  selector:
    name: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306