apiVersion: v1
kind: service
metadata: 
  name: frontend
  labels:
    name: frontend
    tier: web
spec:
  selector:
    name: nginx
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.configmap.port }}  