# apiVersion: v1
# kind: Service
# metadata: 
#   name: frontend
#   labels:
#     name: frontend
#     tier: web
# spec:
#   type: LoadBalancer
#   selector:
#     name: nginx
#     tier: web
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: {{ .Values.configmap.port }}  


apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
    tier: web
spec:
  type: LoadBalancer
  selector:
    name: frontend
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.configmap.port }}