apiVersion: v1
kind: Service
metadata: 
  name: frontend
  labels:
    name: frontend
    tier: web
spec:
  selector:
    type: LoadBalancer
    name: nginx
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.configmap.port }}  